#!/usr/bin/env python3
"""Inject CAMERA + INTERNET permissions and the Scene Viewer <queries>
block into the AndroidManifest generated by `flutter create`."""
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as f:
    s = f.read()

block = (
    '    <uses-permission android:name="android.permission.CAMERA" />\n'
    '    <uses-permission android:name="android.permission.INTERNET" />\n'
    '    <queries>\n'
    '        <intent>\n'
    '            <action android:name="android.intent.action.VIEW" />\n'
    '            <data android:scheme="https" android:host="arvr.google.com" />\n'
    '        </intent>\n'
    '    </queries>\n'
)

if "android.permission.CAMERA" in s:
    print("Manifest already patched")
else:
    s = s.replace("    <application", block + "    <application", 1)
    with open(path, "w", encoding="utf-8") as f:
        f.write(s)
    print("Manifest patched")
